name: Deploy Nuxt 3 to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run generate

      - name: Verify dist directory exists
        run: |
          if [ ! -d "./dist" ]; then
            echo "Error: dist directory not found"
            exit 1
          else
            echo "dist directory exists"
          fi

      - name: Upload `./dist` folder to GitHub Pages Artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./dist

      - name: Deploy to GitHub Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
